## IPBMA_7: CT Sinogram
### Author: Liu Cong and Ulloa Ferrer,Leonardo

In [1]:
import numpy as np
import matplotlib.pyplot as pyplot

In [6]:
import sys, os
from auxFiles.auxFnc import *

try:
    auxFnc = os.path.join(sys.path[0], 'auxFiles', 'auxFnc.py')
    phantomsFnc = os.path.join(sys.path[0], 'auxFiles', 'phantomsFnc.py')
    %run {auxFnc}
    %run {phantomsFnc}
except:
    auxFnc = os.path.join('.', 'auxFiles', 'auxFnc.py')
    phantomsFnc = os.path.join('.', 'auxFiles', 'phantomsFnc.py')
    %run {phantomsFnc}
    %run {auxFnc}

In [7]:
# X-RAY SOURCE

kVp= 100
I0= 75000  
N0, eE= source(kVp, I0)

print(N0, eE)

75000 40.0


In [8]:
# OBJECT

edge_size= 256
eE= 40
obj= cube_phantom_h(edge_size, eE)

In [9]:
# CT INTERACTOR

def interactor_CT(N0, obj, h, nProjections):
  print(N0, obj, h, nProjections)

nProjections= 180
h= 128
qSinograma= interactor_CT(N0, obj, h, nProjections)

75000 [[[0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  ...
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]]

 [[0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  ...
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]]

 [[0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  [0.284928 0.284928 0.284928 ... 0.284928 0.284928 0.284928]
  ...
  [0.284928 0.284928 0.284928 ... 0.284928