## IPBMA_5: Projection Radiography
### Author: Liu Cong and Ulloa Ferrer,Leonardo

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sys, os

try:
    auxFnc = os.path.join(sys.path[0], 'auxFiles', 'auxFnc.py')
    phantomsFnc = os.path.join(sys.path[0], 'auxFiles', 'phantomsFnc.py')
    plotFnc = os.path.join(sys.path[0], 'auxFiles', 'plotFnc.py')
    %run {auxFnc}
    %run {phantomsFnc}
    %run {plotFnc}
except:
    auxFnc = os.path.join('.', 'auxFiles', 'auxFnc.py')
    phantomsFnc = os.path.join('.', 'auxFiles', 'phantomsFnc.py')
    plotFnc = os.path.join('.', 'auxFiles', 'plotFnc.py')
    %run {auxFnc}
    %run {phantomsFnc}
    %run {plotFnc}

In [4]:
edge_size = 256
energy = 40

phantom_nh = cube_phantom_nh(edge_size, energy)

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\ulloa\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip\\auxFiles\\coef\\coefAtenuacionSoft.csv'

### SOURCE

In [2]:
# source(kVp, N0)
# return number of photoms (N0), efective energy (eE)

kVp= 40
I0= 250  
N0, eE= source(kVp, I0)

print(N0, eE)

250 16.0


#### CUBE PHANTOM

In [6]:
# OBJECT
# phantom(size, eE)
# return phantomData

size= 256
obj= cube_phantom_nh(size, eE)

1.615228 0.0017434 1.50032


### QUANTUM IMAGE. FRONTAL VIEW.

In [8]:
# Interaction
# return qImage -> Quantum Image, ideal conditions

prj= 'frontal'
qImage= interactor_PR(N0, obj, prj)

N0: 250
obj: [[[1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  ...
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]]

 [[1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  ...
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]]

 [[1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.50032   1.50032   ... 0.0017434 0.0017434 0.0017434]
  [1.50032   1.5003